#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

exec 1>&2
COUNTER=0
declare -a KEYFILES
for FILE in `find . -type f` ; do
    # Check if the file contains 'the key'
    if `grep -q ${TWITCH_ACCESS_TOKEN} $FILE`
    then
      echo $FILE ' contains a key!'
      KEYFILES[$COUNTER]=$FILE
      COUNTER=$(( $COUNTER + 1 ))
    fi
done

if [[ $COUNTER > 0 ]];
then
  echo ""
  echo "Files with key found"
  echo ""
  exit 1
fi

`go build -o streaming examples/streaming/main.go; rm -f examples/streaming/streaming`
EXBUILD=$?
if [[ $EXBUILD > 0 ]];
then
  echo ""
  echo "Failed to build example"
  echo ""
  exit 1
fi

exit
